name: Checked C Clang CI [WINDOWS]

on:
  workflow_dispatch:
    inputs:
      clang_branch:
        description: 'Clang Branch name'
        required: true
        default: 'main'
      checkedc_branch:
        description: 'Checked-C Branch name'
        required: true
        default: 'main'
      checkedc_repo:
        description: 'Checked-C Repo name'
        required: true
        default: 'https://github.com/secure-sw-dev/checkedc.git'
      clang_repo:
        description: 'Clang Repo name'
        required: true
        default: 'https://github.com/secure-sw-dev/checkedc-llvm-project.git'
      testType:
        description: 'Test Type'
        required: true
        default: 'CheckedC_clang'
        options: ['CheckedC_clang', 'CheckedC_LLVM', 'CheckedC_tests', 'CheckedC']
      Architechture:
        description: 'Architecture'
        required: true
        default: 'X86_64'
        options: ['X86', 'X86_64']

env:
  builddir: "${{github.workspace}}/b/ninja"
  BUILDCONFIGURATION: "Release"
  BUILD_BINARIESDIRECTORY: "${{github.workspace}}/b"
  BUILD_SOURCESDIRECTORY: "${{github.workspace}}"
  TEST_TARGET_ARCH:  ${{ github.event.inputs.Architechture}}
  RUN_LOCAL:  "no"
  TEST_SUITE: ${{ github.event.inputs.testType}}
jobs:
  # Cleanup files left behind by prior runs
  clean:
    name: Clean
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        run: |
          rm -rf ${{env.builddir}}
          mkdir -p ${{env.builddir}}
          rm -rf ${{env.BUILD_BINARIESDIRECTORY}}
          mkdir -p ${{env.BUILD_BINARIESDIRECTORY}}
          rm -rf ${{env.BUILD_SOURCESDIRECTORY}}
          mkdir -p ${{env.BUILD_SOURCESDIRECTORY}}

  test_CheckedC_Clang_on_windows :
    name: Build Checked C clang and test only checkedc tests on windows
    needs: clean
    runs-on: windows-latest
    steps:
      - name: Checkout Checked C Clang code
        uses: actions/checkout@v2
        with:
          path: ${{env.BUILD_SOURCESDIRECTORY}}
      - name: Run setup-and-test.sh script
        env:
          TEST_SUITE: ${{ github.event.inputs.testType}}
          TEST_TARGET_ARCH: ${{ github.event.inputs.Architechture}}
          CLANG_BRANCH: ${{ github.event.inputs.clang_branch}}
          CHECKEDC_BRANCH: ${{ github.event.inputs.checkedc_branch}}
          $CLANG_REPO: ${{ github.event.inputs.clang_repo}}
          $CHECKEDC_REPO: ${{ github.event.inputs.checkedc_repo}}
        shell: cmd
        run: |
         cd ${{env.BUILD_SOURCESDIRECTORY}}\clang\automation\Windows
         build-and-test.bat
